<a href="https://colab.research.google.com/github/Souzalua/ENG437--Ciencias-de-dados/blob/main/Estudo_de_Caso_aulas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ANALISE DE DBO

**Programadora** - Luana Nascimento Barbosa Souza

O projeto foi realizado a partir de um banco de dados coletado pela professora **Karla Esquerre**.


Universidade Federal da Bahia- UFBA

####**O objetivo do trabalho é predizer o comportamento da DBO de entrada**
Com base no entendimento da proposta, buscamos agora entender como as variáveis se conectam com o nosso objetivo.


*   Existe colinearidade entre as colunas do Data Frame e a DBO de entrada?
*   Qual o comportamento das variáveis com o tempo?

Ao final da aula 2 você terá as seguintes habilidades:
* Como subir um arquivo em um repositório no GitHub
* Como importar um arquivo de um repositório no GitHub
* Como importar um arquivo do Google Drive
* Exploração de dados

# 1- Importando bibliotecas

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Importando database

Exploração do banco de dados

In [4]:
#passo 1- carrega o link
link="https://github.com/Souzalua/ENG437--Ciencias-de-dados/raw/refs/heads/main/Dados%20Brutos.xlsx"
tabela=pd.read_excel(link)
display(tabela)

,Datein,FR(m3/dia),BODin (ppm),CODin (ppm),SSin(ppm),pHin,NAmin(ppm),NNin (ppm),Pin (ppm),Colin(ppm),...,Pap (ton/dia),Unnamed: 15,Dateout,BODout(ppm),CODout (ppm),SSout(ppm),Colout(ppm),Tout(°C),Condout,FRout(m3/dia)
0,1996-09-01,79757,236.0,465.0,NaN,6.65,NaN,NaN,NaN,356.0,...,962.1,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996-09-02,78818,270.0,483.0,NaN,6.04,NaN,0.2600,NaN,433.0,...,986.8,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1996-09-03,82039,292.0,571.0,NaN,5.39,NaN,0.2900,NaN,287.0,...,1065.0,NaN,1996-09-03,74.0,245.0,NaN,311.0,33.5,1190.0,84096.8495
3,1996-09-04,79501,264.0,461.0,NaN,5.92,NaN,0.7500,NaN,406.0,...,879.7,NaN,1996-09-04,88.0,237.0,NaN,298.0,33.0,1140.0,79542.4680
4,1996-09-05,82461,299.0,471.0,181.0,6.11,NaN,NaN,NaN,406.0,...,985.8,NaN,1996-09-05,67.0,221.0,37.0,297.0,33.0,1115.0,83813.8935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,2000-07-27,52215,367.0,751.0,250.0,7.44,0.149,NaN,NaN,367.0,...,1077.7,NaN,2000-07-27,159.0,476.0,NaN,159.0,32.0,2230.0,52220.1835
1426,2000-07-28,53216,324.0,751.0,145.0,7.38,0.192,NaN,1.54,324.0,...,945.4,NaN,2000-07-28,150.0,478.0,NaN,150.0,32.0,2390.0,53216.0000
1427,2000-07-29,51561,344.0,701.0,96.0,7.36,NaN,NaN,NaN,344.0,...,1062.5,NaN,2000-07-29,137.0,446.0,NaN,137.0,32.0,2340.0,51561.0000
1428,2000-07-30,51654,303.0,703.0,105.0,7.29,NaN,NaN,NaN,303.0,...,1061.8,NaN,2000-07-30,124.0,411.0,NaN,124.0,31.0,2270.0,51654.0000
1429,2000-07-31,51662,324.0,689.0,118.0,7.28,0.260,0.7488,NaN,324.0,...,937.2,NaN,2000-07-31,147.0,451.0,NaN,147.0,32.0,1971.0,51662.0000

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
link="/content/drive/MyDrive/Ciencias de dados/Dados Brutos.xlsx"
tabela=pd.read_excel(link)
display(tabela)

,Datein,FR(m3/dia),BODin (ppm),CODin (ppm),SSin(ppm),pHin,NAmin(ppm),NNin (ppm),Pin (ppm),Colin(ppm),...,Pap (ton/dia),Unnamed: 15,Dateout,BODout(ppm),CODout (ppm),SSout(ppm),Colout(ppm),Tout(°C),Condout,FRout(m3/dia)
0,1996-09-01,79757,236.0,465.0,NaN,6.65,NaN,NaN,NaN,356.0,...,962.1,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996-09-02,78818,270.0,483.0,NaN,6.04,NaN,0.2600,NaN,433.0,...,986.8,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1996-09-03,82039,292.0,571.0,NaN,5.39,NaN,0.2900,NaN,287.0,...,1065.0,NaN,1996-09-03,74.0,245.0,NaN,311.0,33.5,1190.0,84096.8495
3,1996-09-04,79501,264.0,461.0,NaN,5.92,NaN,0.7500,NaN,406.0,...,879.7,NaN,1996-09-04,88.0,237.0,NaN,298.0,33.0,1140.0,79542.4680
4,1996-09-05,82461,299.0,471.0,181.0,6.11,NaN,NaN,NaN,406.0,...,985.8,NaN,1996-09-05,67.0,221.0,37.0,297.0,33.0,1115.0,83813.8935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,2000-07-27,52215,367.0,751.0,250.0,7.44,0.149,NaN,NaN,367.0,...,1077.7,NaN,2000-07-27,159.0,476.0,NaN,159.0,32.0,2230.0,52220.1835
1426,2000-07-28,53216,324.0,751.0,145.0,7.38,0.192,NaN,1.54,324.0,...,945.4,NaN,2000-07-28,150.0,478.0,NaN,150.0,32.0,2390.0,53216.0000
1427,2000-07-29,51561,344.0,701.0,96.0,7.36,NaN,NaN,NaN,344.0,...,1062.5,NaN,2000-07-29,137.0,446.0,NaN,137.0,32.0,2340.0,51561.0000
1428,2000-07-30,51654,303.0,703.0,105.0,7.29,NaN,NaN,NaN,303.0,...,1061.8,NaN,2000-07-30,124.0,411.0,NaN,124.0,31.0,2270.0,51654.0000
1429,2000-07-31,51662,324.0,689.0,118.0,7.28,0.260,0.7488,NaN,324.0,...,937.2,NaN,2000-07-31,147.0,451.0,NaN,147.0,32.0,1971.0,51662.0000

Métodos de correlação

---

method : {'pearson', 'kendall', 'spearman'}

    * pearson : Correlação linear padrão- medirá o grau de linearidade entre duas variáveis. (Se os dados formam linha reta) -1 a 1

    * kendall : Correlação Tau de Kendall-  Mede a força da relação baseada no ranqueamento dos dados. (conjuntos pequenos ou quando há valores repetidos)
    * spearman : Também baseada em  ranks, mas foca na relação monotônica. Ou seja, se uma variável aumenta, a outra também aumenta, mesmo que não seja de forma linear. (categóricas ordinais x nominais)



Interpretando o valor de ρearson

negativo implica que o aumento de uma leva a diminuição de outra

0.9 a 1 positivo ou negativo indica uma correlação muito forte.

0.7 a 0.9 positivo ou negativo indica uma correlação forte.

0.5 a 0.7 positivo ou negativo indica uma correlação moderada.

0.3 a 0.5 positivo ou negativo indica uma correlação fraca.

0 a 0.3 positivo ou negativo indica uma correlação desprezível

nesse caso, os parâmetros que têm relação com a BDO são:
BODin, CODin, colin,CODout

- Quais atributos melhor se correlacionam com a DBO de entrada, por quê?
- A partir dessa análise inicial quais atributos você removeria da sua análise?
- Como você trataria os outliers das colunas?
- Quais hipóteses podem ser consideradas para dar seguimento ao estudo?